lan:
  - name: veth1
    addr: 10.0.0.1/8
    dhcp: 
      enabled: false
  - name: eth2
    addr: 172.15.2.1/24
    dhcp: 
      enabled: true
      start: 172.15.2.2
      count: 20
      dns: 8.8.8.8
    staticDhcpEntries:
      - ip: 172.15.2.10
        mac: 00:15:5d:13:30:21
wan:
  name: eth1
  addr: 192.168.1.80/24
portForwardingRules:
  - name: testing
    internalPortStart: 3000 # end is implied
    externalPortStart: 2000
    externalPortEnd: 2010
    protocol: tcp
    internalIP: 172.15.2.10
  - name: ssh
    internalPortStart: 22 # end is implied
    externalPortStart: 44
    externalPortEnd: 44
    protocol: tcp
    internalIP: 172.15.2.10
  - name: rejectme
    internalPortStart: 1234 # end is implied
    externalPortStart: 1234
    externalPortEnd: 1234
    protocol: udp
    internalIP: 172.15.2.10

